Repository rimba-engg/rimba-frontend, pull requests merged in 2025-04, with the labels that each got.

#71 novilla pre poc change
  app/(auth)/reporting/air-permits/page.tsx
  app/(auth)/reporting/air-permits/so2_calculator.tsx
Labels: bug, enhancement

#72 Stage
  app/(auth)/reporting/air-permits/page.tsx
  app/(auth)/reporting/air-permits/so2_calculator.tsx
  components/layout/sidebar.tsx
Labels: enhancement

#80 Lokesh master
  app/(auth)/regsqa/page.tsx
  app/components/CitationList.tsx
  app/components/CitationPreviewCard.tsx
  app/components/CitationTooltip.tsx
  app/components/MessageContent.tsx
  app/components/ui/scroll-area.tsx
  app/globals.css
  package-lock.json
  package.json
Labels: enhancement

#90 ADD NOTE
  app/(auth)/audit/checklist/components/checklist-client.tsx
Labels: dependencies

#96 Minor: Remove selected site from local storage on customer selection page
  app/select-customer/page.tsx
Labels: bug

#98 Lokesh master
  app/select-customer/page.tsx
  components/layout/navbar.tsx
Labels: bug
