Repository rimba-engg/rimba-frontend, pull requests merged in 2025-03, with the labels that each got.

#34 Document type
  app/(auth)/library/outgoing-contract/WarehouseDropdown.tsx
  app/(auth)/library/outgoing-contract/dynamic-wrapper.tsx
  app/(auth)/library/outgoing-contract/types.ts
Labels: enhancement

#35 minor dynamic wrapper fix
  app/(auth)/library/incoming-contract/dynamic-wrapper.tsx
  app/(auth)/library/incoming-contract/page.tsx
Labels: bug

#36 added loader
  app/(auth)/library/outgoing-contract/dynamic-wrapper.tsx
Labels: enhancement

#41 Mass Balance module
  app/(auth)/reporting/mass-balance/components/MassBalanceStats.tsx
  app/(auth)/reporting/mass-balance/components/MassBalanceTable.tsx
  app/(auth)/reporting/mass-balance/page.tsx
  app/(auth)/reporting/storage-inventory/page.tsx
  app/(auth)/transactions/dynamic-wrapper.tsx
  app/(auth)/transactions/page.tsx
Labels: enhancement

#43 document numbers in ai extractor + minor fix
  app/(auth)/ai-extractor/page.tsx
  app/(auth)/ai-extractor/types.ts
  app/(auth)/reporting/storage-inventory/page.tsx
Labels: bug, enhancement

#47 minor loaders
  app/(auth)/ai-extractor/components/DocumentTypeModal.tsx
  app/(auth)/ai-extractor/document-type/dynamic-wrapper.tsx
  app/(auth)/audit/checklist/components/task-form-modal.tsx
  app/(auth)/audit/checklist/components/task-sidebar.tsx
  app/(auth)/audit/projects/components/checklist-sidebar.tsx
  app/(auth)/audit/projects/components/modals/delete-modal.tsx
  app/(auth)/audit/projects/components/modals/project-form-modal.tsx
Labels: bug, enhancement

#48 loader in login and select customer
  app/login/page.tsx
  app/select-customer/components/customer-select.tsx
Labels: bug, enhancement

#52 implemented api
  app/(auth)/library/outgoing-contract/dynamic-wrapper.tsx
  app/(auth)/library/outgoing-contract/types.ts
Labels: enhancement

#55 ai Table
  app/(auth)/library/extractions/oldpage.tsx
  app/(auth)/library/extractions/page.tsx
  components/table/MockData.ts
  components/table/QueryTable.tsx
Labels: enhancement

#56 extraction view and QueryTable enhancements
  app/(auth)/library/extractions/page.tsx
  components/table/QueryTable.tsx
Labels: enhancement

#57 Air permits
  app/(auth)/reporting/air-permits/page.tsx
  components/table/QueryTable.tsx
Labels: enhancement

#62 Querytabke in rng mass baance
  app/(auth)/reporting/rng-mass-balance/page.tsx
Labels: enhancement

#67 SSO INTEGRATION
  app/(auth)/ai-extractor/components/DocumentUploadModal.tsx
  app/(auth)/audit/checklist/components/task-sidebar.tsx
  app/(auth)/library/document/dynamic-wrapper.tsx
  app/(auth)/library/documents/page.tsx
  app/(auth)/library/extractions/oldpage.tsx
  app/(auth)/library/incoming-contract/dynamic-wrapper.tsx
  app/(auth)/library/incomings/page.tsx
  app/(auth)/library/outgoing-contract/dynamic-wrapper.tsx
  app/(auth)/reporting/air-permits/page.tsx
  app/(auth)/reporting/mass-balance/page.tsx
  app/(auth)/reporting/rng-qap/page.tsx
  app/ClientAuthProvider.tsx
  app/callback/page.tsx
  app/layout.tsx
  app/login/page.tsx
  app/page.tsx
  app/select-customer/page.tsx
  components/layout/dashboard-guard.tsx
  components/layout/navbar.tsx
  components/layout/notifications.tsx
  lib/api.ts
  lib/auth.ts
  lib/types.ts
  package-lock.json
  package.json
Labels: documentation, enhancement
